### PR TITLE
Removed xib

### PR DESCRIPTION
**Pull request by hslightnin**

### CODE REVIEW

**Comment by hslightnin** [comment]
I needed to be able to customize it a bit more. take a look before merging.

**Comment by knn90** [comment]
Thank you. Look good to me. I will update description later

**Comment by hslightnin** [comment]
Constraints need to be added

On Sat, Oct 15, 2016 at 5:17 PM +0300, "knn" notifications@github.com wrote:

Thank you. Look good to me. I will update description later

**Comment by knn90** [comment]
I think you set position by onCenterPosition & offCenterPosition. So why any constraint need to be added ?

**Comment by hslightnin** [comment]
The width/height would / could change. 

On Sat, Oct 15, 2016 at 5:23 PM +0300, "knn" notifications@github.com wrote:

I think you set position by onCenterPosition & offCenterPosition. So why any constraint need to be added ?

**Comment by knn90** [comment]
Could you please implement it. I'm focusing on another project right now :). Thank you

**Pull request merged**
